---
title: "Project"
author: "Adham Suliman"
date: "May 27, 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!"pacman" %in% rownames(installed.packages())) {
  install.packages("pacman")
}
pacman::p_load(factoextra, dlookr, pairs, dplyr, reshape,cluster, factoextra,xgboost, lme4,MuMIn, walkscoreAPI)
df <- read.csv('C:/Users/u353822/Documents/GitHub/University-of-Chicago1/University of Chicago/Marketing Analytics/project/Airline.csv', header = T, stringsAsFactors= F)
df <- na.omit(df[(df$airline_name=='frontier-airlines')|(df$airline_name=='spirit-airlines')|(df$airline_name=='delta-air-lines')|(df$airline_name=='american-airlines')|(df$airline_name=='united-airlines')|(df$airline_name=='allegiant-air')|(df$airline_name=='jetblue-airways')|(df$airline_name=='westjet')|(df$airline_name=='air-canada-rouge'),])
df$cabin_flown <- as.factor(df$cabin_flown)
```



```{r}
ulcc <- df[(df$airline_name=='frontier-airlines')|(df$airline_name=='jetblue-airways')|(df$airline_name=='allegiant-air')|(df$airline_name=='westjet')|(df$airline_name=='air-canada-rouge'),]
train_ind <- sample(seq_len(nrow(ulcc)), size = floor(nrow(ulcc)*.33))
train_ulcc <-ulcc[train_ind, ]
test_ulcc <- ulcc[-train_ind, ]

legacy <- df[(df$airline_name=='united-airlines')|(df$airline_name=='american-airlines')|(df$airline_name=='delta-air-lines'),]

train_ind <- sample(seq_len(nrow(legacy)), size = floor(nrow(legacy)*.33))
train_legacy <-legacy[train_ind, ]
test_legacy <- legacy[-train_ind, ]
```


K means clustering algorithm on ULCC carriers
```{r}
train_ind <- sample(seq_len(nrow(df)), size = floor(nrow(df)*.33))
train <- df[train_ind,8:11] 
test <- df[-train_ind,8:11]
km.num.of.clust <- 2:10
km.results <- 
  lapply(km.num.of.clust, function(x){
  kmeans.results <- list()
  kmeans.results$k <- x
  kmeans.train <- kmeans(train, center = x, nstart = 100)
  kmeans.results$train.VAF <- kmeans.train$betweenss/kmeans.train$totss
  kmeans.test <- kmeans(test, center = kmeans.train$centers, nstart = 100)
  kmeans.results$test.VAF <- kmeans.test$betweenss/kmeans.test$totss
  #return(kmeans.german.result)
  return(list(x1 = kmeans.results$k, Train.VAF = kmeans.results$train.VAF, Test.VAF = kmeans.results$test.VAF))
  })
km.results1 <- data.frame(matrix(unlist(km.results), nrow=9, byrow=T))
colnames(km.results1) <- c("Clusters","Train.VAF", "Test.VAF")
km.results2 <- melt(km.results1, id=c("Clusters"))
colnames(km.results2) <- c("K.Clusters","K.VAF.Group","K.VAF")
ggplot(km.results2) + geom_smooth(aes(x=K.Clusters,y=K.VAF, colour=K.VAF.Group)) + scale_colour_manual(values=c("red","green"))
```

```{r}
pca.ulcc <- princomp(train)
summary(pca.ulcc)
pca.ulcc$loadings
```


```{r}
km <- kmeans(train, center = 4, nstart = 100) 
fviz_cluster(km,train)
```


logistic regression by cluster
```{r}
train1 <- data.frame(df[train_ind,],km$cluster)
for (x in 1:4){
  z <- train1[train1$km.cluster==x,]
model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',z)
  print(length(z$km.cluster))  
  print(summary(model))
  print(r.squaredGLMM((model)))
}
model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',train1)
print(summary(model))
```

Linear regression by cluster
```{r}
train1 <- data.frame(df[train_ind,],km$cluster)
colnames(train1)
for (x in 1:4){
  z <- train1[train1$km.cluster==x,]
  model <- lmer(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating+(1|cabin_flown),z)
  print(length(z$km.cluster))  
  print(summary(model))
  print(r.squaredGLMM((model)))
}
model <- lm(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,train_ulcc1)
print(summary(model))

```


```{r}
train1 <- data.frame(df[train_ind,],km$cluster)
colnames(train1)
for (x in 1:4){
  z <- train1[train1$km.cluster==x,]
  model <- lm(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,z)
  print(length(z$km.cluster))  
  print(summary(model))
  print(r.squaredGLMM((model)))
}
```




K means clustering algorithm on ULCC carriers
```{r}
train.ulcc <- train_ulcc[,8:12] 
test.ulcc <- test_ulcc[,8:12]
km.num.of.clust <- 2:10
km.results.ulcc <- 
  lapply(km.num.of.clust, function(x){
  kmeans.results <- list()
  kmeans.results$k <- x
  kmeans.train <- kmeans(train.ulcc, center = x, nstart = 100)
  kmeans.results$train.VAF <- kmeans.train$betweenss/kmeans.train$totss
  kmeans.test <- kmeans(test.ulcc, center = kmeans.train$centers, nstart = 100)
  kmeans.results$test.VAF <- kmeans.test$betweenss/kmeans.test$totss
  #return(kmeans.german.result)
  return(list(x1 = kmeans.results$k, Train.VAF = kmeans.results$train.VAF, Test.VAF = kmeans.results$test.VAF))
  })

km.results1.ulcc <- data.frame(matrix(unlist(km.results.ulcc), nrow=9, byrow=T))
colnames(km.results1.ulcc) <- c("Clusters","Train.VAF", "Test.VAF")
km.results2.ulcc <- melt(km.results1.ulcc, id=c("Clusters"))
colnames(km.results2.ulcc) <- c("K.Clusters","K.VAF.Group","K.VAF")
ggplot(km.results2.ulcc) + geom_smooth(aes(x=K.Clusters,y=K.VAF, colour=K.VAF.Group)) + scale_colour_manual(values=c("red","green"))
```

```{r}
pca.ulcc <- princomp(train.ulcc)
summary(pca.ulcc)
pca.ulcc$loadings
```


```{r}
km.ulcc <- kmeans(train.ulcc, center = 4, nstart = 100) 
fviz_cluster(km.ulcc,train.ulcc)
```

logistic regression by cluster
```{r}
train_ulcc1 <- data.frame(train_ulcc,km.ulcc$cluster)
for (x in 1:4){
  z <- train_ulcc1[train_ulcc1$km.ulcc.cluster==x,]
model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',z)
  print(length(z$km.ulcc.cluster))  
  print(summary(model))
}
model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',train_ulcc1)
print(summary(model))
```

Linear regression by cluster
```{r}

for (x in 1:4){
  z <- train_ulcc1[train_ulcc1$km.ulcc.cluster==x,]
  model <- lmer(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating+(1|airline_name),z, REML=F)
  print(length(z$km.ulcc.cluster))  
  print(r.squaredGLMM((model)))
  
}
model <- lm(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,train_ulcc1)
print(summary(model))
```


```{r}
k.test <- unlist(list())
for(x in 4:6){
  k.test[[x]] <- kmeans(train.ulcc, centers =x)
}
k.pairs <- list()
k.pairs <-
  for(x in 4:6){
    pairs(train_ulcc, col = k.test[[x]]$cluster, main =paste(x," Clusters"))
  }
```






K means clustering algorithm on Legacy carriers
```{r}
train.legacy <- train_legacy[,8:12] 
test.legacy <- test_legacy[,8:12]
km.num.of.clust <- 2:10
km.results.legacy <- 
  lapply(km.num.of.clust, function(x){
  kmeans.results <- list()
  kmeans.results$k <- x
  kmeans.train <- kmeans(train.legacy, center = x, nstart = 100)
  kmeans.results$train.VAF <- kmeans.train$betweenss/kmeans.train$totss
  kmeans.test <- kmeans(test.legacy, center = kmeans.train$centers, nstart = 100)
  kmeans.results$test.VAF <- kmeans.test$betweenss/kmeans.test$totss
  #return(kmeans.german.result)
  return(list(x1 = kmeans.results$k, Train.VAF = kmeans.results$train.VAF, Test.VAF = kmeans.results$test.VAF))
  })

km.results1.ulcc <- data.frame(matrix(unlist(km.results.ulcc), nrow=9, byrow=T))
colnames(km.results1.ulcc) <- c("Clusters","Train.VAF", "Test.VAF")
km.results2.ulcc <- melt(km.results1.ulcc, id=c("Clusters"))
colnames(km.results2.ulcc) <- c("K.Clusters","K.VAF.Group","K.VAF")
ggplot(km.results2.ulcc) + geom_smooth(aes(x=K.Clusters,y=K.VAF, colour=K.VAF.Group)) + scale_colour_manual(values=c("red","green"))
```

```{r}
pca.legacy <- princomp(train.legacy)
summary(pca.legacy)
pca.legacy$loadings
```


```{r}
km.legacy <- kmeans(train.legacy, center = 4, nstart = 100) 
fviz_cluster(km.legacy,train.legacy)
```



```{r}
#train_legacy1[train_legacy1$km.legacy.cluster==3,'airline_name']
```


logistic regression by cluster
```{r}
train_legacy1 <- data.frame(train_legacy,km.legacy$cluster)

for (x in 1:4){
  z <- train_legacy1[train_legacy1$km.legacy.cluster==x,]
model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',z)
  print(length(z$km.legacy.cluster))
  print(summary(model))
}

model <- glm(recommended ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,family='binomial',train_legacy1)
print(summary(model))
```


Linear regression by cluster
```{r}
for (x in 1:4){
  z <- train_legacy1[train_legacy1$km.legacy.cluster==x,]
model <- lmer(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating+(1|airline_name),z, REML=F)
  print(length(z$km.legacy.cluster))  
  print(summary(model))
  print(r.squaredGLMM((model)))
  
}
model <- lm(overall_rating ~seat_comfort_rating+ cabin_staff_rating+ food_beverages_rating+inflight_entertainment_rating+value_money_rating,train_ulcc1)
print(summary(model))
```

